export { getDb } from "./lib/db/postgres"

export {
  createNoteForUser,
  deleteNoteForUser,
  listNotesByUser,
  listNotesMissingEmbeddingsByUser,
  parseNoteInput,
  searchNotesByEmbedding,
  updateNoteEmbeddingsForUser,
  updateNoteForUser,
} from "./sql/note"
export { listCategoriesByWorkspace } from "./sql/category"
export { listStatusesByWorkspace } from "./sql/status"
export { listTagsByWorkspace } from "./sql/tag"
export { listWorkspacesByUser } from "./sql/workspace"
export { findUserByIdentifier, getUserById, updateUserPreferencesById } from "./sql/user"

export type {
  UserNoteCategoryLinkV1Row,
  PostgresDbSchema,
  UserNoteTagLinkV1Row,
  UserWorkspaceV1Row,
  WorkspaceNoteCategoryV1Row,
  WorkspaceNoteStatusV1Row,
  WorkspaceNoteTagV1Row,
  UserNoteV1Row,
  UserV1Row,
} from "./generated/typescript/db-types"
export type {
  CategoriesRequest,
  CategoriesResponse,
  CategoryRecord,
  WorkspaceRecord,
  StatusRecord,
  BootstrapResponse,
  StatusesResponse,
  StatusResponse,
  WorkspaceResponse,
  WorkspacesResponse,
  WorkspacesRequest,
  CreateWorkspaceRequest,
  UpdateWorkspaceRequest,
  DeleteWorkspaceRequest,
  CreateStatusRequest,
  UpdateStatusRequest,
  DeleteStatusRequest,
  CreateCategoryRequest,
  CreateCategoryResponse,
  TagsRequest,
  TagsResponse,
  TagRecord,
  NoteCategoryRef,
  CreateTagRequest,
  CreateTagResponse,
  CreateNoteRequest,
  DeleteCategoryRequest,
  DeleteCategoryResponse,
  DeleteTagRequest,
  DeleteTagResponse,
  EmbeddingMaintenanceRequest,
  EmbeddingMaintenanceResponse,
  DeleteNoteRequest,
  DeleteResponse,
  ErrorResponse,
  NoteTagRef,
  NoteInput,
  NoteRecord,
  NoteResponse,
  NotesRequest,
  NotesResponse,
  SearchRequest,
  SearchResponse,
  SemanticSearchResult,
  TokenLoginRequest,
  TokenLoginResponse,
  TokenRevokeResponse,
  UpdateUserPreferencesRequest,
  SessionRequest,
  SessionResponse,
  UserPreferences,
  UpdateCategoryRequest,
  UpdateCategoryResponse,
  UpdateTagRequest,
  UpdateTagResponse,
  UpdateNoteRequest,
  UserSummary,
  NotesAppPreferences,
} from "./contracts/notes-app"
export type { NoteEmbeddingBackfillRow, NoteEmbeddingWriteInput } from "./sql/note"
