export { getDb } from "./lib/db/postgres";

export {
  createNoteForUser,
  deleteNoteForUser,
  listNotesByUser,
  listNotesMissingEmbeddingsByUser,
  parseNoteInput,
  searchNotesByEmbedding,
  updateNoteEmbeddingsForUser,
  updateNoteForUser,
} from "./sql/note";
export { listTaxonomyByUser } from "./sql/taxonomy";
export { listTaxonomyLevelsForUser } from "./sql/taxonomy-level";
export { listTagsByUser } from "./sql/tag";
export { findUserByIdentifier, getUserById, updateUserPreferencesById } from "./sql/user";

export type {
  UserNoteCategoryV1Row,
  UserTaxonomyV1Row,
  UserTaxonomyLevelV1Row,
  PostgresDbSchema,
  UserNoteTagLinkV1Row,
  UserNoteTagV1Row,
  UserNoteV1Row,
  UserV1Row,
} from "./generated/typescript/db-types";
export type {
  TaxonomyRequest,
  TaxonomyResponse,
  TaxonomyRecord,
  TaxonomyLevelRecord,
  TaxonomyLevelsResponse,
  TaxonomyPathRequest,
  TaxonomyPathResponse,
  TaxonomySuggestRequest,
  TaxonomySuggestResponse,
  CreateTaxonomyRequest,
  CreateTaxonomyResponse,
  MergeIdRemapEntry,
  MergeIdRemaps,
  MergeSessionResponse,
  TagsRequest,
  TagsResponse,
  TagRecord,
  CreateTagRequest,
  CreateTagResponse,
  CreateNoteRequest,
  DeleteTaxonomyRequest,
  DeleteTaxonomyResponse,
  DeleteTaxonomyMode,
  DeleteTagRequest,
  DeleteTagResponse,
  EmbeddingMaintenanceRequest,
  EmbeddingMaintenanceResponse,
  DeleteNoteRequest,
  DeleteResponse,
  ErrorResponse,
  NoteTagRef,
  NoteInput,
  NoteRecord,
  NoteResponse,
  NotesRequest,
  NotesResponse,
  SearchRequest,
  SearchResponse,
  SemanticSearchResult,
  TokenLoginRequest,
  TokenLoginResponse,
  TokenRevokeResponse,
  UpdateUserPreferencesRequest,
  SessionRequest,
  SessionResponse,
  UserPreferences,
  UpdateTaxonomyRequest,
  UpdateTaxonomyResponse,
  UpdateTaxonomyLevelRequest,
  UpdateTagRequest,
  UpdateTagResponse,
  UpdateNoteRequest,
  UserSummary,
  NotesAppPreferences,
} from "./contracts/notes-app";
export type { NoteEmbeddingBackfillRow, NoteEmbeddingWriteInput } from "./sql/note";
